name: model-supervisé RL
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python SCI1402_TN3_Mbountcha_John_Willy.py
          # Write your CML report
          echo "## Metriques:" >> reports.md
          cat Metric_Classification.txt >> report.md
          git config --global user.email "mjohnwilly@yahoo.fr"
          git config --global user.name "mjohnwilly"
          git add reports.md Metric_Classification.txt
          git commit -m "pousser vers github repository"
          git push origin HEAD:master
